# klasifikasi orange or grapefruit

cause our dataset is csv so we use pandas library to change it to dataframe

we use ``read_csv()``

In [19]:
    import pandas as pd
    df = pd.read_csv('citrus.csv')

see overview of our dataset

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   name      10000 non-null  object 
 1   diameter  10000 non-null  float64
 2   weight    10000 non-null  float64
 3   red       10000 non-null  int64  
 4   green     10000 non-null  int64  
 5   blue      10000 non-null  int64  
dtypes: float64(2), int64(3), object(1)
memory usage: 468.9+ KB


use ``head()`` to show our dataframe.

in our dataset the label is first column

In [22]:
df.head(10000)

name  diameter  weight  red  green  blue
0         orange      2.96   86.76  172     85     2
1         orange      3.91   88.05  166     78     3
2         orange      4.42   95.17  156     81     2
3         orange      4.47   95.60  163     81     4
4         orange      4.48   95.76  161     72     9
...          ...       ...     ...  ...    ...   ...
9995  grapefruit     15.35  253.89  149     77    20
9996  grapefruit     15.41  254.67  148     68     7
9997  grapefruit     15.59  256.50  168     82    20
9998  grapefruit     15.92  260.14  142     72    11
9999  grapefruit     16.45  261.51  152     74     2

[10000 rows x 6 columns]

**remember, jst cant process string**

so we have to change string value to numeric <br>
run process below to change it.

In [23]:
    df.name[df.name == 'orange'] = 0
    df.name[df.name == 'grapefruit'] = 1

C:\Users\Azwinck\AppData\Local\Temp\ipykernel_14592\2502857679.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.name[df.name == 'orange'] = 0
C:\Users\Azwinck\AppData\Local\Temp\ipykernel_14592\2502857679.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.name[df.name == 'grapefruit'] = 1


until this step, we cant process this dataset because our dataset still dataframe shape.

dataset must be in the form of an array.

fortunately, it can do easly using attribute ``values`` of dataframe.<br>
values return numpy array yg dikonvert from dataframe

In [24]:
    dataset = df.values

to see changed dataframe in form of array  

In [25]:
dataset

array([[0, 2.96, 86.76, 172, 85, 2],
       [0, 3.91, 88.05, 166, 78, 3],
       [0, 4.42, 95.17, 156, 81, 2],
       ...,
       [1, 15.59, 256.5, 168, 82, 20],
       [1, 15.92, 260.14, 142, 72, 11],
       [1, 16.45, 261.51, 152, 74, 2]], dtype=object)

then we have to seperate between attribute and label in dataset.

from data exploration before, we know that last 5 column are attribute column

In [26]:
    # pilih 5 kolom terakhir sebagai atribut
    X = dataset[:,1:6]
    # bilangan sebelum koma untuk memilih baris pada dataframe
    # bilangan setelah koma untuk memilih kolom pada dataframe

dont forget to seperate label from dataset.

in dataset, the label in first column

In [27]:
    y = dataset[:,0]

next, there is important step that we must do for jst can learn dataset well. this step is ``normalization``

we can use ``fit_transform()`` of objek ``MinMaxScaler`` from libary preprocessing SKLearn to normalize our data

In [28]:
    # Normalization
    from sklearn import preprocessing
    min_max_scaler = preprocessing.MinMaxScaler()
    X_scale = min_max_scaler.fit_transform(X)
    X_scale

array([[0.        , 0.        , 0.74025974, 0.63529412, 0.        ],
       [0.07042254, 0.00738197, 0.66233766, 0.55294118, 0.01851852],
       [0.10822832, 0.04812589, 0.53246753, 0.58823529, 0.        ],
       ...,
       [0.93624907, 0.97133047, 0.68831169, 0.6       , 0.33333333],
       [0.96071164, 0.99216023, 0.35064935, 0.48235294, 0.16666667],
       [1.        , 1.        , 0.48051948, 0.50588235, 0.        ]])

after we have attribute and label seperately, we also will seperate again our data become data training and data testing to evaluate our model.

``train_test_split`` function can help us to do it easly.
in this step, we use 30% of entire data as data testing.

In [29]:
    # pisahkan data training dan testing
    from sklearn.model_selection import train_test_split
    X_train, X_test, Y_train, Y_test = train_test_split(X_scale, y, test_size=0.3)

cause we changed values of column name to numeric in fourth step, it means we changed label *from string to boolen type*, then we have to change it to *float32*

In [30]:
Y_test

array([0, 0, 1, ..., 1, 0, 0], dtype=object)

In [31]:
    import numpy as np
     
    Y_train = Y_train.astype(np.float32)
    Y_test = Y_test.astype(np.float32)

In [32]:
Y_test

array([0., 0., 1., ..., 1., 0., 0.], dtype=float32)

finally, processing data steps already done. Now, we start build our jst model.

import library below

In [12]:
    from keras.models import Sequential
    from keras.layers import Dense

**make model architect**

we will develop model sequential which have 3 layers.

activation function in firt 2 layer is ``relu`` but you can explore to use anothers activation function.

for last layer, the paremater values is 1 where output of our jst is 1 buah bilangan numerik. Activation function that we use is ``sigmoid`` because it memetakan probabilitas of 0 to 1. it very suitable for biner clasification problem

In [13]:
    model = Sequential([    
                        Dense(32, activation='relu', input_shape=(5,)),    
                        Dense(32, activation='relu'),    
                        Dense(1, activation='sigmoid'),])

after build model architect, we have to determine optimizer and loss function to our model.

for optimizer we use ``sgd`` (stochastic gradient descent). it is general optimizer and suitable for dataset which have small dataset.

for loss function we use ``binary_crossentropy`` because problem in this case is masalah 2 kelas (biner)

besides that, we have to show accuration in each step training model process by add ``metrics`` parameter and fill it with string 'accuracy' 

In [14]:
    model.compile(optimizer='sgd',
                  loss='binary_crossentropy',
                  metrics=['accuracy'])

after we already done, we can start training model by run code below

In [15]:
    model.fit(X_train, Y_train, epochs=100)

Epoch 1/100
219/219 [==============================] - 6s 8ms/step - loss: 0.6726 - accuracy: 0.7096
Epoch 2/100
219/219 [==============================] - 1s 7ms/step - loss: 0.6357 - accuracy: 0.8633
Epoch 3/100
219/219 [==============================] - 1s 7ms/step - loss: 0.5859 - accuracy: 0.8961
Epoch 4/100
219/219 [==============================] - 1s 7ms/step - loss: 0.5091 - accuracy: 0.9137
Epoch 5/100
219/219 [==============================] - 1s 7ms/step - loss: 0.4166 - accuracy: 0.9223
Epoch 6/100
219/219 [==============================] - 2s 7ms/step - loss: 0.3334 - accuracy: 0.9241
Epoch 7/100
219/219 [==============================] - 1s 6ms/step - loss: 0.2749 - accuracy: 0.9247
Epoch 8/100
219/219 [==============================] - 1s 6ms/step - loss: 0.2388 - accuracy: 0.9251
Epoch 9/100
219/219 [==============================] - 1s 7ms/step - loss: 0.2177 - accuracy: 0.9259
Epoch 10/100
219/219 [==============================] - 1s 7ms/step - loss: 0.2042 - accura

the last, we evaluate out model then see if model underfit or overfit.

evaluate function return 2 values. 1. loss value and accuracy

In [16]:
    model.evaluate(X_test, Y_test)
    # elemen pertama adalah loss dan elemen kedua adalah akurasi

94/94 [==============================] - 1s 5ms/step - loss: 0.1771 - accuracy: 0.9310


[0.17711390554904938, 0.9309999942779541]

### Test Prediction

In [37]:
df[4:5]

name  diameter  weight  red  green  blue
4    0      4.48   95.76  161     72     9

In [38]:
df[9995:9996]

name  diameter  weight  red  green  blue
9995    1     15.35  253.89  149     77    20

In [39]:
t1 = [[ 15.35,253.89,149,77,20]] #anggur[1]
t0 = [[ 4.48,95.76,161,72,9]]    #orange[0]

In [40]:
print(model.predict(t1))

[[1.]]


In [41]:
print(model.predict(t0))

[[0.]]
